# [START runtime]
runtime: nodejs
vm: true
# [END runtime]


env_variables:
    GCLOUD_PROJECT: twitter-writes-hamlet

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$
