# [START runtime]
runtime: nodejs
vm: true
# [END runtime]

manual_scaling:
  instances: 1

env_variables:
    GCLOUD_PROJECT: twitter-writes-hamlet-us

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$
